# This is a basic workflow to help you get started with Actions

name: POC Github actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
    - master 
    - 'feature/**'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    runs-on: ubuntu-latest
    name: Run Robot tests
 # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout and run code
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - uses: addnab/docker-run-action@v3
        with:
          image: ppsahoo/robot_selenium_tests_in_chrome:latest
          options: -e ROBOT_UID=1000 -e ROBOT_GID=1000 -v ${{ github.workspace }}/tests:/opt/robotframework/tests:Z
          run: |
            runrobottests.sh
